### ISSUE TITLE
천천히 해봐요 ㅎㅎ

### ISSUE THREAD

**Issue by hkw2028** [AlgorStudy/solution_to_algo_problems#1]
어짜피 누구 보여줄려고 하는 거 아니니까 시간 두고 할 수 있는 만큼만 하자고요 ㅎㅎ

**Comment by Sangmin0602** [comment]
책 한번 살펴봤는데 어떻게 접근을 해야할지 모르겠네..ㅋㅋㅋ 내용은 잼있겠어요.. 문제는 어려운데..

**Comment by hkw2028** [comment]
ㅋㅋㅋ 그냥 요약한다고 생각하시죠 뭐 저도 잘 모르고 ㅋㅋ 
2명 중에 제대로 아는 사람 없다고 생각하시고 그냥 지르세요 ㅎㅎㅎ
